#!/bin/bash
# Bootstrap script for setting up a new macOS machine
set -e

# Logging helpers
info() { echo -e "\033[0;34mℹ️  $1\033[0m"; }
success() { echo -e "\033[0;32m✅ $1\033[0m"; }
error() { echo -e "\033[0;31m❌ $1\033[0m"; exit 1; }
warn() { echo -e "\033[0;33m⚠️  $1\033[0m"; }

# Trap errors
trap 'error "An error occurred during the setup process. Please check the output above."' ERR

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

info "Starting macOS setup..."

# Profile Selection
LOCAL_CONFIG="$SCRIPT_DIR/local_config.sh"
if [ ! -f "$LOCAL_CONFIG" ]; then
    info "No local profile configuration found."
    echo "Please select the profile for this machine:"
    echo "  1) Home"
    echo "  2) Work"
    read -p "Enter choice [1-2]: " choice
    case $choice in
        1) PROFILE="home" ;;
        2) PROFILE="work" ;;
        *) error "Invalid choice. Exiting." ;;
    esac
    
    echo "export DOTFILES_PROFILE=\"$PROFILE\"" > "$LOCAL_CONFIG"
    success "Profile configured: $PROFILE"
else
    source "$LOCAL_CONFIG"
    if [ -z "$DOTFILES_PROFILE" ]; then
        warn "local_config.sh exists but DOTFILES_PROFILE is not set."
    else
        info "Active Profile: $DOTFILES_PROFILE"
    fi
fi

# Install Homebrew if not present
if ! command -v brew &> /dev/null; then
    info "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" || error "Failed to install Homebrew"
    eval "$(/opt/homebrew/bin/brew shellenv)"
    success "Homebrew installed"
else
    success "Homebrew already installed"
fi

# Install chezmoi if not present (needed for dotfiles setup)
if ! command -v chezmoi &> /dev/null; then
    info "Installing chezmoi..."
    brew install chezmoi || error "Failed to install chezmoi"
fi

# Initialize chezmoi with this repo
info "Setting up dotfiles with chezmoi..."
if [ -d "$HOME/.local/share/chezmoi" ]; then
    info "chezmoi already initialized, applying updates..."
    chezmoi apply || error "Failed to apply chezmoi updates"
else
    info "Initializing chezmoi..."
    chezmoi init --source="$SCRIPT_DIR" --apply || error "Failed to initialize chezmoi"
fi
success "Dotfiles configured"

# Install packages from Brewfile (Generated by chezmoi)
info "Installing packages from Brewfile..."
if brew bundle --file="$HOME/Brewfile"; then
    success "Packages installed successfully"
else
    warn "Some packages failed to install. Check Brewfile output."
fi

# Apply macOS defaults
info "Applying macOS preferences..."
if "$SCRIPT_DIR/macos-defaults.sh"; then
    success "macOS preferences applied"
else
    warn "Some macOS preferences could not be applied."
fi

# Configure Hyperkey
info "Configuring Hyperkey..."
if "$SCRIPT_DIR/hyperkey-defaults.sh"; then
    success "Hyperkey configured"
else
    warn "Hyperkey configuration failed."
fi

# Set fish as default shell
info "Setting fish as default shell..."
FISH_PATH="$(which fish)"
if [ -z "$FISH_PATH" ]; then
    error "Fish shell not found. Is it in the Brewfile?"
fi

if ! grep -q "$FISH_PATH" /etc/shells; then
    info "Adding fish to /etc/shells..."
    echo "$FISH_PATH" | sudo tee -a /etc/shells
fi

if [ "$SHELL" != "$FISH_PATH" ]; then
    info "Changing default shell to fish..."
    chsh -s "$FISH_PATH"
    success "Default shell changed to fish"
else
    success "Fish is already the default shell"
fi

echo ""
success "Setup complete!"
echo ""
info "Next steps:"
echo "  1. Restart your terminal"
echo "  2. Open Neovim and let plugins install"
